# Generated by Django 2.0.2 on 2018-03-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField()),
                ('code', models.TextField()),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('qualifies', models.TextField(null=True)),
                ('explanation', models.TextField()),
                ('array_field', models.TextField(null=True)),
                ('aggregate_definitions', models.TextField(null=True)),
                ('aggregate_filters', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField()),
                ('entity', models.TextField()),
                ('record_spec', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_server.Ruleset'),
        ),
        migrations.AddField(
            model_name='definition',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_server.Ruleset'),
        ),
    ]
