# Generated by Django 2.0.2 on 2018-03-07 16:55

from django.db import migrations

from rules_server.sql.sql_function_defs import ANNUALIZE_FUNCTION_DEF


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(ANNUALIZE_FUNCTION_DEF)
    ]
