# Generated by Django 2.0.2 on 2018-03-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
