# Generated by Django 2.0.2 on 2018-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0002_rule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='record_spec',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
