# Generated by Django 2.0.3 on 2018-03-20 02:56

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0002_auto_20180317_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntaxSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='jsonschema')),
                ('code', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_server.Ruleset')),
            ],
        ),
    ]
