# Generated by Django 2.0.3 on 2018-04-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0002_auto_20180317_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='sufficient',
        ),
    ]
