# Generated by Django 2.0.3 on 2018-03-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0002_auto_20180307_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('array_field', models.TextField(null=True)),
                ('aggregate_definitions', models.TextField(null=True)),
                ('aggregate_filters', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rule',
            name='aggregate_definitions',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='aggregate_filters',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='array_field',
        ),
        migrations.AddField(
            model_name='datasource',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_server.Rule'),
        ),
    ]
