# Generated by Django 2.0.2 on 2018-03-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_server', '0004_rule_qualifies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField()),
                ('code', models.TextField()),
                ('explanation', models.TextField()),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_server.Ruleset')),
            ],
        ),
    ]
